name: Update Top 10 Raves

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update-top-raves:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script to update statistik.html
        env:
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_KEY }}
          PLAUSIBLE_SITE_ID: ravebro.de
        run: python .github/scripts/generate_top_raves_table.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add statistik.html
          git commit -m "Update Top 10 Raves in statistik.html [auto]" || echo "No changes to commit"
          git push